### ISSUE TITLE
Modification of Wait's parameters during a workflow execution does not trigger a ModifiedDecisionException

### ISSUE THREAD

**Issue by geomagilles** [zenaton/zenaton-javascript#41]
Example:
```
module.exports = Workflow("WaitWorkflow", async function() {
  await new Wait().seconds(5).execute();
  throw new Error("Error in TaskE");
});
```
Then after the error, comment the throw and change wait to 10 seconds.

When you retry, the workflow terminates nicely - it should not and should indicate a modified decider.

**Comment by Ciboulette** [comment]
ok @geomagilles , understood! I will have a look.

So I still do not understand why it was throwing a modified decider exception in Production & not in development?

**Comment by Ciboulette** [comment]
Good news from what I can see, we do not have this behaviour in the php-sdk

**Comment by Ciboulette** [comment]
This is the job sent in Node.js to the agent in the `execute`HTTP CALL
```%{"branch" => 0, "duration" => 10, "event" => nil, "input" => "{\"v\":\"1.0.0\",\"s\":[{\"k\":[\"event\"],\"v\":[null]}],\"o\":\"@zenaton#0\"}", "maxProcessingTime" => nil, "name" => "_Wait", "position" => "1", "sync" => true, "timestamp" => nil, "type" => "wait"}```

This is the job sent in PHP to the agent in the `execute`HTTP CALL
```%{"branch" => 0, "duration" => 5, "event" => nil, "input" => "{\"a\":{\"event\":null,\"_buffer\":[[\"seconds\",5]]},\"s\":[]}", "maxProcessingTime" => nil, "name" => "Zenaton\\Tasks\\Wait", "position" => "1", "sync" => true, "timestamp" => nil, "type" => "wait"}```

As you can see, the parameter sent with the wait are not included in the input serialization in Node.js, this is why the hash is the same and so it does not generate a ModifiedDeciderException. 

Now I'm wondering why it was generating one in production, we should have a deeper look to Amine's workflow

**Comment by Ciboulette** [comment]
So I dug a little bit more, 

In Node.js, the JobBox.js in the Agent has `data[ATTRIBUTE_INPUT] = serializer.encode(this.job.data);`

And for a wait, `this.job.data` has only the `event` properties, not the `_buffer` like in PHP.

I believe this is something we don't want. After having a look to the waitClass here:
https://github.com/zenaton/zenaton-node/blob/master/src/async/Tasks/Wait.js

You can see that it apply a `WaitTimestamp` trait:
https://github.com/zenaton/zenaton-node/blob/master/src/async/Traits/WithTimestamp.js, where properties `_buffer` is used

And the Trait class is defined here, https://github.com/zenaton/zenaton-node/blob/master/src/async/Services/Trait.js 

You can see that the apply method is: 
```
mix.apply(this, [baseClass.prototype].concat(traits));

  return baseClass;
```

I may be wrong because it's voodoo JS to me, but I believe this is injecting trait properties to the base `this` of the waitClass and we maybe want to be injected in `this.data`

@jalric your help will be appreciated ;)

**Comment by jalric** [comment]
Fixed.
